---
r2-epe:
  hostname: 172.16.10.1
  username: cisco
  password: Appel132
  data:
    secret: Appel123
  connection_options:
    napalm:
      extras:
        optional_args:
          secret: Appel123
    netmiko:
      extras:
        secret: Appel123
  groups:
    - router