---
r1-dev:
  hostname: 192.168.10.121
  groups:
    - router
    - deventer

r2-epe:
  hostname: 192.168.10.122
  groups:
    - router
    - epe

r3-erm:
  hostname: 192.168.10.123
  groups:
    - router
    - ermelo

S1:
  hostname: 192.168.10.124
  groups:
    - switch
    - epe

S2:
  hostname: 192.168.10.124
  groups:
    - switch
    - ermelo